title: Adv. GIS project

description: Luis Xavier Villasenor | PhD Student
show_downloads: True
github:
  zip_url: https://github.com/luisvillalxv/Adv-GIS-project/archive/refs/heads/main.zip
theme: jekyll-theme-architect
